spring:
  application:
    name: jdbc-demo
  datasource:
    # 数据源类型,一般不用指定
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库驱动,默认根据jdbc-url自动识别
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
